disabled_rules:
    - force_cast
    - force_try
    - multiple_closures_with_trailing_closure
excluded:
    - Velik/Strings.swift
opt_in_rules:
    - let_var_whitespace
    - vertical_whitespace_closing_braces
    - vertical_parameter_alignment_on_call
    - first_where
    - flatmap_over_map_reduce
    - legacy_cggeometry_functions
    - legacy_constant
    - legacy_random
nesting:
    type_level: 3

identifier_name:
    excluded:
        - id
        - x
        - y
        - z
